services:
    redis:
        image: redis:latest
        networks:
          - jupyter
        container_name: redis-dictionary-container
        ports:
          - '6379:6379'
        command: redis-server --save 60 1 --loglevel warning
        volumes:
          - redis_data:/data
networks:
    jupyter:
        name: jupyter-network
volumes:
    redis_data: