version: "3"

services:
  jupyter:
    image: jupyter/all-spark-notebook:python-3.10.6
    ports:
      - "40400:4040"
      - "8890:8888"
    environment:
      - JUPYTER_TOKEN=pwd
    volumes:
      # set this path to the (absolute) path on your computer
      # - /Absolute/Path/To/Where/Your/Notebook/Files/Will/Be/Saved:/home/jovyan/work
      - ./work:/home/jovyan/work
      - python-libraries:/opt/conda/lib/python3.10/site-packages
    # the following volumes daclaration is used only for named anonymous storages
    #  - jupyter-data:/home/jovyan/work
    networks:
      - jupyter
    container_name: jupyter-container

# to be used for named anonymous storages
volumes:
  python-libraries:
#  jupyter-data: {}


networks:
  jupyter:
    name: jupyter-network


